service: weather-records-app

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1
  environment:
    DB_URI: ${file(./config.json):DB_URI_DEV}

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)