service: weather-records-app

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1
  environment:
    DB_URI: ${file(./config.json):DB_URI_DEV}
    WEATHER_API_KEY: ${file(./config.json):WEATHER_API_KEY}

functions:
  processWeatherRecord:
    handler: handler.processWeatherRecord
    events:
      # Invoke Lambda function every minute
      - schedule: rate(30 minutes)