service: weather-records-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  stage: dev
  region: eu-north-1
  environment:
    DB_URI: ${file(./config.json):DB_URI_DEV}
    WEATHER_API_KEY: ${file(./config.json):WEATHER_API_KEY}

functions:
  processWeatherRecord:
    handler: handler.processWeatherRecord
    events:
      # Invoke Lambda function at :00 and :30 of every hour
      - schedule: cron(0,30 * * * ? *)
  getWeatherRecords:
    handler: handler.getWeatherRecords
    events:
      - http:
          path: /
          method: get
          cors: true